name: Install dependencies engine
description: Install dependencies engine

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        export CC=${{ env.cc }}
        export CXX=${{ env.cxx }}
        conan install . --update --build=missing
